name: Zenodo JSON

on: [push, pull_request]

jobs:
  json_verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install yajl-tools

      - name: Run json_verify
        run: |
          cat .zenodo.json | json_verify


